USE pasibrzuch;

CREATE TABLE KLIENCI (
	ID int PRIMARY key not null AUTO_INCREMENT,
    Imie varchar(50) NOT NULL,
    Nazwisko varchar(50) NOT NULL,
    Adres text,
    Telefon text,
    Email text
);

CREATE TABLE POTRAWY (
  ID int PRIMARY KEY not null AUTO_INCREMENT,
  Nazwa varchar(50) NOT NULL,
  Cena float NOT NULL,
  Opis text,
  Dostepnosc boolean
);

CREATE TABLE KATEGORIE (
  ID int PRIMARY KEY not null AUTO_INCREMENT,
  Nazwa varchar(50) NOT NULL
);

CREATE TABLE POTRAWY_KATEGORIE (
  ID_POTRAWY int NOT NULL,
  ID_KATEGORII int NOT NULL,
  FOREIGN KEY (ID_POTRAWY) REFERENCES POTRAWY(ID),
  FOREIGN KEY (ID_KATEGORII) REFERENCES KATEGORIE(ID)
);

CREATE TABLE ZAMOWIENIA (
  ID int PRIMARY KEY not null AUTO_INCREMENT,
  ID_KLIENTA int NOT NULL,
  Data_zamowienia date NOT NULL,
  Data_realizacji date,
  Status varchar(50) NOT NULL,
  FOREIGN KEY (ID_KLIENTA) REFERENCES KLIENCI(ID)
);

CREATE TABLE ZAMOWIENIA_POTRAWY (
  ID_ZAMOWIENIA int NOT NULL,
  ID_POTRAWY int NOT NULL,
  Ilosc int NOT NULL,
  FOREIGN KEY (ID_ZAMOWIENIA) REFERENCES ZAMOWIENIA(ID),
  FOREIGN KEY (ID_POTRAWY) REFERENCES POTRAWY(ID)
);
