version: '3'
services:
  apache:
    build: .
    hostname: php-app
    user: "33:33"
    ports:
      - "80:80"
    networks:
      - backend
      - frontend
    links:
      - mysql
    env_file:
      - .env
    environment:
      - PUID=33
      - PGID=33
    restart: always
    volumes:
      - ./production/api/:/var/www/api/
      - ./production/public/:/var/www/html
  
  mysql:
    image: mariadb:latest
    hostname: mysql
    networks:
      - backend
    env_file:
      - .env
    restart: always
    volumes:
      - ./database:/var/lib/mysql
      # - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    links:
      - mysql
    restart: always
    env_file:
      - .env

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure
